cc_library(
    name = "theme",
    srcs = [
        ":theme.cpp",
    ],
    hdrs = [
        ":theme.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core/terminal:terminal",
    ],
)