cc_library(
    name = "terminal",
    deps = [],
    srcs = [
        ":color.cpp",
    ],
    hdrs = [
        ":terminal.hpp",
        ":color.hpp",
    ],
    visibility = ["//visibility:public"],
)