cc_library(
    name = "terminal",
    srcs = [
        ":color.cpp",
        ":raw.cpp",
    ],
    hdrs = [
        ":terminal.hpp",
        ":color.hpp",
        ":raw.hpp",
        ":event.hpp",
    ],
    visibility = ["//visibility:public"],
)