cc_binary(
    name = "ryze",
    srcs = [
        ":main.cpp"
    ],
    deps = [
        "//src/core/terminal:terminal",
        "//src/core/editor:editor",
        "//src/core/ui:ui",
        "//src/core/theme:theme",
    ],
)