cc_library(
    name = "screen",
    srcs = [
        ":screen.cpp",
    ],
    hdrs = [
        ":screen.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/core/terminal:terminal",
    ],
)